apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: apache
  namespace: laravel-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: triple3a/laravel-app
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    run: front-service
  namespace: laravel-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache
